--基础设置
require("basic")
--快捷键管理
require("keybindings")
--皮肤设置
require("colorscheme")
--插件管理
require("plugins")
--插件配置
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
--lsp
require("lsp/setup")
